### ISSUE TITLE
Can't return tuples in a server's method

### ISSUE THREAD

**Issue by JeysonFlores** [python-sdbus/python-sdbus#10]
Hello, I'm doing some tests with this library in order to implement it on one of my current Linux apps. 
I wrote this code which according to the documentation of types should work:
```Python
    @dbus_method_async(
        result_signature="(ss)",
        result_args_names=["result"],
    )
    async def tuple_test(self) -> tuple:
        return ("hello", "world")
```
However it throws me this error:
```Bash
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<DbusMethodAsyncBinded._call_from_dbus() done, defined at /home/jeyson/.local/lib/python3.8/site-packages/sdbus/dbus_proxy_async.py:137> exception=TypeError("Message append error, expected tuple got 'hello'")>
Traceback (most recent call last):
  File "/home/jeyson/.local/lib/python3.8/site-packages/sdbus/dbus_proxy_async.py", line 172, in _call_from_dbus
    reply_message.append_data(
TypeError: Message append error, expected tuple got 'hello'
```

If I assign the tuple to a variable to check its type IT IS a tuple so for some reason it isn't recognizing the variable as a tuple.
Is there anything that I'm missing or is it a bug?
Thanks

**Comment by igo95862** [comment]
> is it a bug?

The issue is that any python function call that returns multiple values is encoded as tuple.

I can't think of any way that python can tell if a function returned a tuple or multiple returns.

I did not add any checks if we need to pack a structure or multiple values.

Try using as a work around: `return (("hello", "world"), )` (returning a tuple of one element of tuple)

Thank you for finding that inconsistency. I will think of better way of handling that.

**Comment by JeysonFlores** [comment]
> Try using this as a work around: return (("hello", "world"), ) (returning a tuple of one element of tuple)

Thanks, it will do the trick, I hope you can improve this little detail in higher versions

**Comment by igo95862** [comment]
I think I will do something like this:

```python

            try:
                reply_message.append_data(
                    self.dbus_method.result_signature, *reply_data)
            except TypeError:
                if self.dbus_method.result_signature.startswith('('):
                    reply_message.append_data(
                        self.dbus_method.result_signature, reply_data)
                else:
                    raise
```
I think the only case there we might mistake return struct for return multiple values is when the result signature only contains a single structure.
