### ISSUE TITLE
[FR] Support generic signal subscription

### ISSUE THREAD

**Issue by asmello** [python-sdbus/python-sdbus#14]
Currently `bus.get_signal_queue_async()` is very strict about requiring the user to specify the **exact** signal that should be listened to. For example, attempting to omit the `member_name` argument to that method by passing None results in this error:

```
TypeError: argument 4 must be str, not None
```

This forces the user to set separate listeners for every signal they care about, knowing the full object path, interface name and signal name. This doesn't scale well.

Consider the use case of listening to changes to GATT characteristics in a BLE device, to keep track of its state (e.g. smart bulb). In this case, the user likely doesn't want to capture changes to a single property of a single device. Most likely, they will want to capture changes across a number of devices (multiple bulbs), and not only one type of change - devices added, removed, characteristic value updates (toggled on/off), adapter status transitions (discovery on/off) and more. With the current implementation, to do that the user must instance new resources for every new device, service and characteristic that is discovered, which can easily become untenable.

Looking over the source code, I'm not sure exactly where this behavior is enforced, perhaps [here](https://github.com/python-sdbus/python-sdbus/blob/9fea8cc2170ba853a9c3d809d884063f86782d62/src/sdbus/sd_bus_internals_bus.c#L441)? What's interesting though is that the core of this function delegates the listener to libsystemd via a call to [`sd_bus_match_signal_async()`](https://manpages.debian.org/stretch-backports/libsystemd-dev/sd_bus_match_signal_async.3.en.html), which does support more flexible signal matching. I can see [some examples elsewhere](https://github.com/systemd/systemd/blob/6bb89282053eb04c7be6e22ce533f5a13463a513/src/shared/bus-wait-for-jobs.c#L102) where NULLs are passed to that function to disable matching on some components of the signal identifier. In fact, [the DBUS specification](https://dbus.freedesktop.org/doc/dbus-specification.html#message-bus-routing-match-rules) explicitly allows for this usage (emphasis added):

> Match rules are added using the AddMatch bus method (see the section called “org.freedesktop.DBus.AddMatch”). Rules are specified as a string of comma separated key/value pairs. **Excluding a key from the rule indicates a wildcard match. For instance excluding the the member from a match rule but adding a sender would let all messages from that sender through.** An example of a complete rule would be "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='Foo',path='/bar/foo',destination=':452345.34',arg2='bar'"

So both in the interest of better supporting the protocol, as well as to enable more scalable applications, can we make the arguments to `bus.get_signal_queue_async()` optional?

**Comment by igo95862** [comment]
Yes, it is definitely possible.

**Comment by igo95862** [comment]
@asmello I added a4540da9031e3f1ffcb6599b60e45ae9c826a7a7 commit. It should allow putting `None` in place of strings.

By the way can you think of any good wildcards matches for Bluez? I can add the to the binds I was working on: https://github.com/python-sdbus/python-sdbus-bluez

Also I need to come up with good high-level interface for making wildcard matches. `get_signal_queue_async` was always intended for backend code.

**Comment by asmello** [comment]
That is awesome, thanks for actioning it so quickly. I intended to submit a PR, but looking at your solution I think it would have taken me a while to figure out the right approach. Will try it out as soon as I can.

> By the way can you think of any good wildcards matches for Bluez? I can add the to the binds I was working on: https://github.com/python-sdbus/python-sdbus-bluez

I need to think about this a bit more. Only just started handling signals. But from a high level, my currently planned use cases are:
- Tracking updates about several properties in the `org.bluez.Device1` interface
  - `Connected`, `Paired`, `RSSI`, maybe `Alias` too
  - I want to keep track of this for all devices without explicitly keeping track of which have appeared/disappeared
  - I'll do a wildcard here for `object_path` and possibly `member_name` too
- Tracking updates about the Value property of specific characteristics I know the UUID for
  - Annoyingly can't do a match with the UUID directly, but can at least subscribe to changes to the `Value` property of any `org.bluez.GattService1` interface and do the filtering after the fact
  - Also annoyingly I think I still have to _enable_ notifying for the properties I want explicitly, but at least it's a one-off thing for each device, so I can just reuse the task that listens to `InterfacesAdded` for that
  - That means the wildcard here just `object_path`
 
In terms of workflow, the way I want to interact with BLE works in two stages, an initial "snapshot" phase, where I use the ObjectManager interface to learn about the existing devices, services and characteristics, populating a local database, and then a "monitoring" phase, where I keep track of changes to properties of interest to keep the local data in sync with the source of truth. Many transitions like `Connected` and changes to `Value` can be inferred from client-driven actions (user presses a button in my UI), but there's always the chance some external actor will interfere (someone turns the device off) which will throw the local state out of sync unless we're actively listening to changes pervasively. If you're curious, I'm having the UI use a websocket to receive those events in realtime, so ultimately I only need a single events queue that captures everything (hence the natural case for wildcards).

> Also I need to come up with good high-level interface for making wildcard matches. get_signal_queue_async was always intended for backend code.

In practical terms, I think one thing of usability you could implement is having a first class way to listen to properties changed hierarchically. So, say, I register `/org/bluez/hci0/dev_XX_YY...` (or even `/org/bluez/`) and then automatically capture changes for any properties of the nested services and characteristics. That is not as well targeted as using the full extent of match rules, but it does simplify the problem quite a lot.

I wouldn't recommend getting rid of the more flexible method, though. The OO treatment is awesome, but not a panacea.

## One other thing

Only tangential, but isn't the `destination_name` argument mislabeled? Unless I'm misunderstanding something, it maps to the `sender` argument in `sd_bus_match_signal_async`, so it seems backwards.

**Comment by asmello** [comment]
This is awesome, seems to be working as expected. This from the same queue:
```python
('org.bluez.Device1', {'Connected': ('b', True)}, [])
('org.bluez.Device1', {'ServicesResolved': ('b', True), 'Paired': ('b', True)}, [])
```
Will close this now, thank you very much.

**Comment by igo95862** [comment]
> I wouldn't recommend getting rid of the more flexible method, though. The OO treatment is awesome, but not a panacea.

I have plan to provide access to low level API but it is not stable right now. I might rename the methods in the future. (for example, `message.get_member()` -> `message.member`) For high level API I try to keep backwards compatibility and track deprecation.

> Only tangential, but isn't the `destination_name` argument mislabeled? Unless I'm misunderstanding something, it maps to the `sender` argument in `sd_bus_match_signal_async()`, so it seems backwards.

I probably copied it from some other method. I can change it without issues because `sd_bus_match_signal_async` takes only positional arguments.

**Comment by igo95862** [comment]
@IB1387 you might be able to leverage this feature.

**Comment by igo95862** [comment]
> Reopening, as there's still something missing before this feature can really be useful. The payload we get in `.get_contents()` doesn't include any reference to the object that generated the signal, so there's no way to know which device it is coming from. I haven't dug very deep, but seems that the message we get from systemd [does have the full source reference](https://github.com/systemd/systemd/blob/main/src/libsystemd/sd-bus/bus-message.h#L66-L70), it's probably just not being used in the parsing function.

There is `sd_bus_message_get_path` I just have not implemented it yet. I can do that this evening.

**Comment by igo95862** [comment]
@asmello I added ce8dbb1a18f26c44c5f965522891c6fb401e9854 which adds new Message properties.

**Comment by asmello** [comment]
You are the best! Will experiment and loop back.

**Comment by asmello** [comment]
Things seem to be working properly. Minor issue I found was type resolution doesn't work for the `data` object here:
```python
payload = message.get_contents()[1]
for signal, data in payload.items():
    print(data[1])  # linter complains data should be `str | int | bytes | float`, but it's actually a tuple
```
This doesn't block anything though, so will go ahead and close this issue again. Really appreciate the responsiveness, thanks again for implementing it.

**Comment by asmello** [comment]
Hmm, spoke too soon. Seems that I'm getting some kind of signal that the library doesn't know how to parse. I have this code:

```python
queue = await bus.get_signal_queue_async(
    "org.bluez",
    None,
    "org.freedesktop.DBus.Properties",
    None,
)
while True:
    try:
        message = await queue.get()
        print(message.get_contents())
    except Exception as e:
        print("Exception", e)
```

Which prints:
```
('org.bluez.Adapter1', {'Discovering': ('b', True)}, [])
Exception Dbus type '\x00' is unknown
('org.bluez.Device1', {'RSSI': ('n', -57), 'TxPower': ('n', 10)}, [])
Exception Dbus type '\x00' is unknown
('org.bluez.Device1', {'RSSI': ('n', -74)}, [])
Exception Dbus type '\x00' is unknown
('org.bluez.Device1', {'RSSI': ('n', -66)}, [])
...
('org.bluez.Device1', {}, ['TxPower', 'RSSI'])
Exception Dbus type '\x00' is unknown
('org.bluez.Adapter1', {'Discovering': ('b', False)}, [])
Exception Dbus type '\x00' is unknown
```

I can just ignore the exception for now, but figured it was worth investigating.

**Comment by igo95862** [comment]
> Minor issue I found was type resolution doesn't work for the `data` object here:

I really really need recursive types support for `mypy` for this. There is an open issue from 2015 https://github.com/python/mypy/issues/731

For now you can insert an `assert isinstance`.

**Comment by igo95862** [comment]
> Hmm, spoke too soon. Seems that I'm getting some kind of signal that the library doesn't know how to parse. I have this code:

This looks identical to this: https://github.com/python-sdbus/python-sdbus/issues/12

The task was garbage collected.

**Comment by asmello** [comment]
Hmm will investigate, I find it hard to believe the task is being garbage collected because I implemented it as a context manager, which works like this:
```python
class DeviceManager:
    @contextmanager
    def cleanup_context(self):
        with self._write_coordinator.cleanup_context():
            change_listener = asyncio.create_task(self._listen_properties_changed())
            try:
                yield
            finally:
                change_listener.cancel()

manager = DeviceManager()
with manager.cleanup_context():
    async for event in manager.events:
        print(event)
```
So there should be no way the task is created more than once, or goes out of scope more than once. Unless Python is being cheeky and garbage collecting a variable in a suspended generator, which would most definitely be a bug.

There's also the fact that I haven't changed the code structure and only started observing this after the new feature was introduced. But I'll close then and track this as a separate issue if I can't figure it out.

**Comment by igo95862** [comment]
There might be some wrong logic in relation with cancellation.

If you can find a reliable reproduction I would be very thankful.

**Comment by asmello** [comment]
Oh nvm, I figured it out, it's a silly thing. I had code for debugging like this:
```
print(message.get_contents())
interface, payload, removed = message.get_contents()
```
Seems that the first call to `.get_contents()` consumes the payload, so the second one fails because there's no content to read anymore.

**Comment by igo95862** [comment]
> Seems that the first call to `.get_contents()` consumes the payload, so the second one fails because there's no content to read anymore.

Yes but that can be fixed.
