### ISSUE TITLE
Equivalent for `bus.add_signal_receiver()`

### ISSUE THREAD

**Issue by wes8ty** [python-sdbus/python-sdbus#20]
Sorry for another question...

Do you have an equivalent for `bus.add_signal_receiver()` in the below example. This will intercept the signal when a peripheral (phone) connects via Bluetooth whether it is already known or new. The method executes a callback when this signal occurs.

```
bus.add_signal_receiver(properties_changed,
dbus_interface = 'org.freedesktop.DBus.Properties',
signal_name = "PropertiesChanged",
path_keyword = "path")

bus.add_signal_receiver(interfaces_added,
dbus_interface = 'org.freedesktop.DBus.ObjectManager',
signal_name = "InterfacesAdded")
```

I was looking in the code and saw this but I can't get it to work.

``` py
class DbusPropertiesInterfaceAsync(
    DbusInterfaceBaseAsync,
    interface_name='org.freedesktop.DBus.Properties',
    serving_enabled=False,
):
    def __init__(self) -> None:
        super().__init__()

        properties_changed_signal = self.properties_changed
        for key, value in getmembers(self):
            if isinstance(value, DbusPropertyAsyncBinded):
                if not value.dbus_property.flags & DbusPropertyEmitsChangeFlag:
                    continue

                value.dbus_property.properties_changed_signal \
                    = properties_changed_signal

    @dbus_signal_async('sa{sv}as')
    def properties_changed(self) -> DBUS_PROPERTIES_CHANGED_TYPING:
        ...
```

``` py
self.__prop_mngr = DbusPropertiesInterfaceAsync()
self.__prop_mngr.export_to_dbus("/")

async for event in self.__prop_mngr.properties_changed:
     self.__log.info(event)
```

**Comment by igo95862** [comment]
Looks like you need a wildcard signal match.

Sadly there is no high level interface. However, you can create a messages queues directly on bus.

```python
properties_changed_message_queue = await self.bus.get_signal_queue_async(
            'org.bluez',  # service name
            None,  #  object_path
            'org.freedesktop.DBus.Properties',  # interface name
            'PropertiesChanged')  # member name

interfaces_added_message_queue = await self.bus.get_signal_queue_async(
            'org.bluez',  # service name
            None,  #  object_path
            'org.freedesktop.DBus.ObjectManager',  # interface name
            'InterfacesAdded')  # member name

```

Now you can poll for raw messages:

```python
while True:
    message = await interfaces_added_message_queue.get()
    print(message.get_contents())
```

**Comment by igo95862** [comment]
I have an idea for high level interface. Something called `catch_any_path` which you return an async iterator of path and signal data. (would also be callable from class itself)

**Comment by wes8ty** [comment]
I think that would be good. Would this support multiple signals? If I was to do:

``` py
while True:
    message = await properties_changed_message_queue.get()
    print(message.get_contents())

    message = await interfaces_added_message_queue.get()
    print(message.get_contents())

```
If no properties were changing, won't this block `interfaces_added_message_queue()` from being serviced? Is there a way to async for multiple signals currently with `async for`? What do you think?

**Comment by igo95862** [comment]
> Is there a way to `async for` multiple signals currently?

Spawn two separated tasks each. (but remember to bind them to variables or they will be garbage collected)

**Comment by igo95862** [comment]
There is also https://docs.python.org/3/library/asyncio-task.html#asyncio.wait

which lets you wait on multiple coroutines.

**Comment by wes8ty** [comment]
Thanks for the articles! Would this be an example of how you would capture a signal? I am scheduling this but nothing is happening. This is using `Network Manager`
```
@dbus_signal_async('o')
    def device_added(self) -> str:
        """Signal when new device has been added with path"""
        raise NotImplementedError
```

``` py
    async def task_nm_device_added(self) -> None:
        try:
            while True:
                async for x in self.__nm.device_added:
                    generic = NetworkDeviceGeneric(x)
                    self.__log.info(generic)

        except asyncio.CancelledError:
            self.__log.info("Stopping Network Mgr Device Added...")
```

**Comment by wes8ty** [comment]
Yes, I called
```
sdbus.set_default_bus(sdbus.sd_bus_open_system())
```

The reason I have the while True is that I am using `aiojobs` lirbary to spawn the jobs. I am trying to get a list of access points and update them accordingly based on device added / removed so I always want to check. If the `async for` finds a signal it will end the job right without the `while True` to keep checking.

**Comment by wes8ty** [comment]
I might be wrong. `async for` is forever right? How would you change the behavior to only check a signal once then exit?

**Comment by igo95862** [comment]
> `async for` is forever right? How would you change the behavior to only check a signal once then exit?

Yes. Just put a `break` or `return` statement.

These examples might be handy: https://github.com/python-sdbus/python-sdbus-networkmanager/tree/master/examples

> I am trying to get a list of access points and update them accordingly based on device added / removed so I always want to check.

So you pluging in and out wifi devices?

**Comment by wes8ty** [comment]
I figured it out. Need to use `access_point_removed` and `access_point_added` signals. I can't believe I forgot about the `break` keyword...ugggg lol
