### ISSUE TITLE
Getting message sender from D-Bus method

### ISSUE THREAD

**Issue by mswiger** [python-sdbus/python-sdbus#21]
Hello! I am trying to implement a D-Bus service where I need to get the caller (message sender) of a D-Bus method. It seems that the low-level sdbus API has a method called [sd_bus_message_get_sender](https://manpages.debian.org/stretch-backports/libsystemd-dev/sd_bus_message_get_sender.3) for this purpose. From what I can tell, methods decorated with `@dbus_method_async` don't seem to have any way of getting this information, but I could certainly be missing something. Is there currently any way to get this information in python-sdbus?

Thank you!

**Comment by igo95862** [comment]
Hello,

Correct me if I am wrong:

1. You are serving some object on D-Bus
2. Someone called your method
3. You want to know the D-Bus sender id of who called the message?

There some properties of the message objects available:

https://github.com/python-sdbus/python-sdbus/blob/e8dcaa0d71b44637425630446853b216a47072bd/src/sdbus/sd_bus_internals.py#L135

The sender property is not implemented yet but it can be very trivial to implement one.

However, those are from low-level API. They are not very useful in the decorated methods. I have a few ideas how the API  for methods might look like but no implementations so far.

**Comment by mswiger** [comment]
Hey! Yeah, that's exactly correct. After some more digging around, it looks like the built in Python dbus API passes a `sender` keyword argument to decorated methods: https://dbus.freedesktop.org/doc/dbus-python/tutorial.html#finding-out-the-caller-s-bus-name

Would something like that make sense here too?

**Comment by igo95862** [comment]
> Would something like that make sense here too?

Maybe.

I am thinking about using generators like `x = yield y`. I would need to prototype to test what would be a better fit.

**Comment by igo95862** [comment]
@mswiger I created a `get-current-message` branch with the dffbfb00525968d3ee162bf65a534c88e4970caa commit. It implements a `get_current_message()` function that returns the currently processed D-Bus message. (using the contextvars)

Example:

```python
message = get_current_message()
print(message.sender)
```

I am not entirely sure if this should be the only call or there should be calls for each property. (`get_current_message_sender`, `get_current_message_member`, ...)

**Comment by mswiger** [comment]
@igo95862 the implementation you have there looks great to me! In terms of the API design, between exposing the `SdBusMessage` data structure and creating a getter for each property, the latter seems a bit cleaner to me (and the sd-bus API itself might help to inform which properties should have getters). However, I think either way would be fine in the end, and I think you have a lot deeper understanding of the API design of this library!

**Comment by igo95862** [comment]
I merged it as is for now. It is not completely finished because it does not work for properties or signals callbacks.

It is also not documented for now.

**Comment by mswiger** [comment]
Awesome, thanks for taking care of this!
