### ISSUE TITLE
Release with catch_anywhere

### ISSUE THREAD

**Issue by IB1387** [python-sdbus/python-sdbus#22]
Hi @igo95862,

I refactored some of my code to use the new catch_anywhere function and it seems to run smoothly so far. As we rely on pip for some CI/CD stuff, when can we roughly expect a new python-sdbus version with this function to be released?

Best regards!

**Comment by igo95862** [comment]
Hello,

This weekend is highly probable.

**Comment by IB1387** [comment]
Sounds great - thanks a lot in advance. I'll close this and monitor the repo for the next release!
