### ISSUE TITLE
Generator output is invalid when a property is named class

### ISSUE THREAD

**Issue by gotthardp** [python-sdbus/python-sdbus#26]
Hello. The D-Bus SMS interface of a ModemManager has a property called `class`
https://www.freedesktop.org/software/ModemManager/doc/latest/ModemManager/gdbus-org.freedesktop.ModemManager1.Sms.html#gdbus-property-org-freedesktop-ModemManager1-Sms.Class

The interface code generator generates this:
```python
    def class(self) -> int:
        raise NotImplementedError
```
That obviously causes the `SyntaxError: invalid syntax` error.

**Comment by igo95862** [comment]
Hello.

This is identical issue to #9.

My stance currently is that automatically generated code must be reviewed and corrected before running. The code generator is mostly to do heavy lifting but polish must be added manually.

**Comment by gotthardp** [comment]
Oh, I see, thanks!
