### ISSUE TITLE
Close bus connection

### ISSUE THREAD

**Issue by mirfatif** [python-sdbus/python-sdbus#30]
`sdbus.get_default_bus().close()` doesn't seem to make any difference after calling `request_default_bus_name()` and `export_to_dbus()`. The interface remains usable.

Is it possible to release the service name and close / free / unref the bus connection completely without killing the native process?

**Comment by igo95862** [comment]
Do you have a code example? `close()` should disconnect the bus.

**Comment by mirfatif** [comment]
I see now. `SdBus` object is held inside a `ContextVar` object. So calling `sdbus.get_default_bus().close()`  from a different thread opens a new bus connection and closes it. I need to keep a global reference to `SdBus` instance to be able to close it from another thread.

Thank you for the response.
