### ISSUE TITLE
Exporting object with multiple interfaces breaks bus

### ISSUE THREAD

**Issue by ivan-avalos** [python-sdbus/python-sdbus#31]
Hey! I've been trying to implement an MPRIS service for a music player, and I need to export an object with two interfaces: `org.mpris.MediaPlayer2` and `org.mpris.MediaPlayer2.Player`. This is my current approach:

```python
class Base(
        DbusInterfaceCommonAsync,
        interface_name='org.mpris.MediaPlayer2',
):
    # ...
    pass
```

```python
class Player(
        DbusInterfaceCommonAsync,
        interface_name='org.mpris.MediaPlayer2.Player',
):
    # ...
    pass
```

```python
class MPRIS(Base, Player):
    # ...
    pass
```

Then, I try to initialize D-Bus and export the object:

```python
mpris = MPRIS()

async def startup():
    await asyncio.request_default_bus_name_async("org.mpris.MediaPlayer2.example")
    mpris.export_to_dbus("/org/mpris/MediaPlayer2")

loop = asyncio.new_event_loop()
loop.run_until_complete(startup())
loop.run_forever()
```

However, in the D-Bus debugger, there is no `org.mpris.MediaPlayer2.example`. If I comment the export line, it appears again. There is no error message whatsoever, it looks like it's working, but it actually isn't. Earlier, I tried exporting two different objects to the same path, and it happened the same.

**Comment by igo95862** [comment]
Hmm. Let me test this once I get some free time.

I did not realize that I did not have a unit test for multiple inheritance.

**Comment by ivan-avalos** [comment]
So, I found out that the real issue was the following:

```python
@dbus_property_async(property_signature='a{sv}')
    def Metadata(self) -> Dict[str, Tuple[str, Any]]:
        ...
```

I guess this needs a separate issue.
