### ISSUE TITLE
Signature `a{sv}` causes D-Bus connection to crash without errors

### ISSUE THREAD

**Issue by ivan-avalos** [python-sdbus/python-sdbus#32]
When I add this to an interface, the D-Bus connection crashes immediately, without any kind of message errors.

```python
@dbus_property_async(property_signature='a{sv}')
    def Metadata(self) -> Dict[str, Tuple[str, Any]]:
        ...
```

_Originally posted by @ivan-avalos in https://github.com/python-sdbus/python-sdbus/issues/31#issuecomment-1374407169_

**Comment by igo95862** [comment]
Hello,

Can you try adding a return statement.

```python
   @dbus_property_async(property_signature='a{sv}')
    def Metadata(self) -> Dict[str, Tuple[str, Any]]:
        return {}
```

**Comment by igo95862** [comment]
> D-Bus connection crashes immediately, without any kind of message errors

Do you have asyncio debug mode activated? https://docs.python.org/3/library/asyncio-dev.html#debug-mode

**Comment by igo95862** [comment]
@ivan-avalos any updates?

I tested it by adding the property to the unit test interface. After adding the return statement there were no more issues.

**Comment by ivan-avalos** [comment]
One of the metadata fields had type `o`, and it was assigned a string. That's possibly what was causing the error. Sorry, I should've posted this update earlier.

**Comment by ivan-avalos** [comment]
I have a question: how do you think I could implement the `mpris:trackid` metadata field? How can I generate an object path for each song?

https://www.freedesktop.org/wiki/Specifications/mpris-spec/metadata/#mpris:trackid

My MPRIS implementation is located under `sublight/dbus_`:

https://fossil.avalos.me/sublightd/dir

**Comment by igo95862** [comment]
According to https://specifications.freedesktop.org/mpris-spec/latest/Track_List_Interface.html

>  Each track in the tracklist has a unique identifier. The intention is that this uniquely identifies the track within the scope of the tracklist. In particular, if a media item (a particular music file, say) occurs twice in the track list, each occurrence should have a different identifier. If a track is removed from the middle of the playlist, it should not affect the track ids of any other tracks in the tracklist.

> As a result, the traditional track identifiers of URLs and position in the playlist cannot be used. Any scheme which satisfies the uniqueness requirements is valid, as clients should not make any assumptions about the value of the track id beyond the fact that it is a unique identifier. 

So you can try to use python's `id()` function. It should provide a unique identifier for any python object although pretty lengthy one.

**Comment by ivan-avalos** [comment]
That's no issue, as I can use Subsonic IDs, but how do I generate a valid object path for each track?

**Comment by igo95862** [comment]
> That's no issue, as I can use Subsonic IDs, but how do I generate a valid object path for each track?

It looks like it can be any valid D-Bus object path.

For example, Celluloid uses `/io/github/CelluloidPlayer/Celluloid/Track/0` as track id.

See the D-Bus specification for valid object paths: https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-marshaling-object-path

There are several helper functions in python-sdbus to work with object paths.

First there is [`sdbus.encode_object_path`](https://python-sdbus.readthedocs.io/en/latest/common_api.html#sdbus.encode_object_path) that can encode any symbols in to object path even those who are not allowed by the specification. (`dbus.service` -> `dbus_2eservice`)

Second, there is [`is_object_path_valid`](https://github.com/python-sdbus/python-sdbus/blob/master/src/sdbus/sd_bus_internals.py#L275) which should verify if your path is correct. However, it is not exported or documented. (not sure why)

**Comment by igo95862** [comment]
Basically track id can be anything you want but:

1. Must be a valid D-Bus object path.
2. Your D-Bus server should be easily understand what object the id actually references.

**Comment by igo95862** [comment]
@ivan-avalos did you encounter any other issues? I added private setters in the d9f283d42d0bd179c4e74bda7151c9694d23f6ce commit. There should be 0.11.0 release this weekend.

**Comment by ivan-avalos** [comment]
No issues so far! My MPRIS implementation is more or less working already. I'll check out next release, try out private setters and let you know how it goes.

![Screenshot_20230119_205209](https://user-images.githubusercontent.com/16617314/213607908-82dd445d-b8fd-45c5-a487-c275055da350.png)

**Comment by ivan-avalos** [comment]
I'm trying the private setters, and apparently the decorators return `None` instead of a callable function.

**Comment by igo95862** [comment]
> I'm trying the private setters, and apparently the decorators return `None` instead of a callable function.

What do you mean? Do you have an example?

**Comment by ivan-avalos** [comment]
Oh, okay, I thought I had to call the setter directly. It's working now, but I just figured out that private setters don't quite work well for my use case, which is notifying clients that a variable changed, without setting it.

Let's suppose that I paused the song using the in-app controls. I want to tell MPRIS clients about the new song, so I do a `set_async`, which in turn, updates the player state, which in turn, triggers another `set_async`, causing an infinite loop. The way I thought I could solve this, was creating special setters that do nothing, but still emit the “property changed” signal.

```python
@PlaybackStatus.setter_private
def EmitPlaybackStatus(self, _: str): return
```

Then, I could do this:

```python
self.PlaybackStatus.set_async("") # new_value doesn't matter!
```

However, the private setter for `PlaybackStatus` would conflict with the public setter:

```python
@PlaybackStatus.setter
def _SetPlaybackStatus(self, s: str):
    self.controllable.mprisPlaybackStatus = s
```

---

Is there a better way to achieve this?

**Comment by igo95862** [comment]
> However, the private setter for `PlaybackStatus` would conflict with the public setter:

According to MPRIS specification `PlaybackStatus` is read only: https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:PlaybackStatus

So it should not have a public setter. Clients should use `Pause` method to pause: https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Method:Pause

Your in-app controls can just call the private setter:

```
await self.PlaybackStatus.set_async("Paused")
```

Although I am not sure if your GUI toolkit supports asyncio.

> I want to tell MPRIS clients about the new song, so I do a set_async, which in turn, updates the player state, which in turn, triggers another set_async, causing an infinite loop.

I don't quite understand how being paused and adding new songs would affect each other. Do you have an example.

**Comment by ivan-avalos** [comment]
I will give you an example of a `Pause()` call from an MPRIS client.

Whenever you send a `Pause()` to the player, the playback status has to be notified to the MPRIS clients. In my player, it happens in the following way:

1. The Player object contains a Controllable object, so it calls its method `mprisPause()`.

```python
@dbus_method_async()
async def Pause(self) -> None:
    self.controllable.mprisPause()
```

2. Control, which inherits Controllable, calls its own `pause()` in response.

```python
def mprisPause(self) -> None:
    self.pause()
```

3. Control contains an MPVPlayer object, of which `pause()` calls its `pause()` method.

```python
def pause(self):
    self.player.pause()
```

4. Now, how do I tell the MPRIS clients that I just paused? Using a callback in Controllable.

```python
propagate_callback: Callable
```

5. The Player object does this at init:

```python
def playerSetup(self, controllable: Controllable):
    self.controllable = controllable
    self.controllable.mprisSeeked = lambda x: self.Seeked.emit(x)
    self.controllable.propagate_callback = lambda: self.propagate()
```

6. I added a decorator to Controllable, which calls `propagate()` after calling the decorated function, so as to tell Player that playback state changed.

```python
@staticmethod
def mprisPropagate(function: Callable) -> Callable:
    @functools.wraps(function)
    def propagated(self: Controllable, *args, **kwargs):
        rv = function(self, *args, **kwargs)
        self.propagate_callback()
        return rv
    return propagated
```

7. So, `pause()` is now this:

```python
@Controllable.mprisPropagate
def pause(self):
    self.player.pause()
```

8. Up until now, the function in Player called on `propagate_callback`, was this:

```python
def propagate(self):
    self.properties_changed.emit(
        ("org.mpris.MediaPlayer2.Player", {
            "PlaybackStatus": ("s", self.controllable.mprisPlaybackStatus),
            "LoopStatus": ("s", self.controllable.mprisLoopStatus),
            "Rate": ("d", self.controllable.mprisRate),
            "Volume": ("d", self.controllable.mprisVolume),
            "Shuffle": ("b", self.controllable.mprisShuffle),
            "Metadata": ("a{sv}", self.dbusified_metadata()),
            "MinimumRate": ("d", self.controllable.mprisMinimumRate),
            "MaximumRate": ("d", self.controllable.mprisMaximumRate),
            "CanGoNext": ("b", self.controllable.mprisCanGoNext),
            "CanGoPrevious": ("b", self.controllable.mprisCanGoPrevious),
            "CanPlay": ("b", self.controllable.mprisCanPlay),
            "CanPause": ("b", self.controllable.mprisCanPause),
            "CanSeek": ("b", self.controllable.mprisCanSeek),
            "CanControl": ("b", self.controllable.mprisCanControl),
        }, [])
    )
```

But let's suppose I use a private or public setter (for any property) in that function:

```python
await self.LoopStatus.set_async(self.controllable.mprisLoopStatus)
```

This would trigger the LoopStatus setter:

```python
@LoopStatus.setter
def _SetLoopStatus(self, s: str):
    self.controllable.mprisLoopStatus = s
```

Which would in turn call the setter in Controllable:

```python
@mprisPlaybackStatus.setter
def mprisPlaybackStatus(self, s: str) -> None:
    if s == "Playing":
        self.playCurrentSong()
    elif s in ("Paused", "Stop"):
        self.pause()
```

And, remember `pause()` had a decorator?

```python
@Controllable.mprisPropagate
def pause(self):
    self.player.pause()
```

This would trigger `propagate_callback` again, and boom: an infinite loop.

**Comment by igo95862** [comment]
I think using decorators makes it way too complicated. I would just use method overloading.

This is how I would do it:

```python
class MyMPRIS(DbusInterfaceCommonAsync):
     def __init__(self, player: MyPlayer):
          self._playback_status = ""
          self.player = player

     @dbus_method_async()
     async def pause(self) -> None:
         self.player.pause()
 
     @dbus_property_async("s")
     def playback_status(self) -> str:
         return self._playback_status

     @playback_status.private_setter
     def _playback_status_set(self, new_value: str) -> None:
         self._playback_status = new_value


class MyPlayer(MPVPlayer):
     def __init__(self, *args, **kwargs, mpris: MyMPRIS):
          super().__init__(*args, **kwargs)
          self.mpris = mpris

     async def pause(self, *args, **kwargs):
          super().pause(*args, **kwargs)
          await self.mpris.set_async("Paused")

```

I don't know if the MPVPlayer class actually supports asyncio.

**Comment by igo95862** [comment]
BTW I recently encountered the similar issue with recursive calls with Qt.

I fixed it by adding a boolean flag:

https://github.com/igo95862/bubblejail/blob/e17a846bf6486aebbb117522543e2b97c1a17786/src/bubblejail/bubblejail_gui_qt.py#L384-L387

**Comment by igo95862** [comment]
I will close this for now. If you have any more questions feel free to use Discussions.
