### ISSUE TITLE
`set_async` on read-only properties

### ISSUE THREAD

**Issue by ivan-avalos** [python-sdbus/python-sdbus#33]
Hey! I'm still implementing MPRIS in my music player, and I find myself wanting to notify the clients about changes in the state of the application. Whenever the player does something internally (play, pause, etc.), I want it to be reflected on the clients connected to the player, so I need to set the properties from within. However, it seems like I can't do that without making the properties externally writeable (i.e. by adding setters). Is there a way to add private setters?

**Comment by igo95862** [comment]
Hello,

Do you mean you want to emit the `org.freedesktop.DBus.Properties.PropertiesChanged` signal for some of the properties that cannot be written from D-Bus? (from reading MPRIS documentation for example `Tracks` property)

Private setters is a nice idea to add. I will see if I can implement them in the new version. Meanwhile you can try emitting signals manually.

This is how it approximately should look like. (pretty )

https://github.com/python-sdbus/python-sdbus/blob/91b9f24d8b0fcf12fd8f913d44d5abc210550119/src/sdbus/dbus_proxy_async_property.py#L159-L175

**Comment by ivan-avalos** [comment]
I was trying to do that, but couldn't get the tuple right. Now it works! Thanks!
