### ISSUE TITLE
code generator for sync 

### ISSUE THREAD

**Issue by zhanglongqi** [python-sdbus/python-sdbus#35]
Do you have a draft version for sync interfaces code generator so I can test?

**Comment by igo95862** [comment]
Hello,

I don't have one.

However, it is pretty straight forward converting async to sync.

1. Remove all signals
2. Remove `_async` suffix from all decorators. (`dbus_method_async` -> `dbus_method`)
3. Remove `async` from all methods.

Maybe I will add a sync generator in next version.
