### ISSUE TITLE
camel_case_to_snake causes issues with all uppercase or all lowercase inputs

### ISSUE THREAD

**Issue by bhattarabi** [python-sdbus/python-sdbus#36]
camel_case_to_snake("methodname") returns "m_e_t_h_o_d_n_a_m_e" and same for all uppercase

**Comment by igo95862** [comment]
Hello.

Since this converter is for interface generator is there a specific D-Bus service that has caused the issues?

**Comment by bhattarabi** [comment]
I see this issue when generating client for a custom D-Bus service whose property names are all in uppercase.
xml:
 <interface name="O.Connector">
  <property name="CONNECTORNAME" type="s" access="readwrite">
   <annotation name="org.freedesktop.DBus.Property.EmitsChangedSignal" value="false"/>
  </property>
  <property name="CONNECTORKIND" type="s" access="readwrite">
   <annotation name="org.freedesktop.DBus.Property.EmitsChangedSignal" value="false"/>
  </property>
  <property name="NUMCONNECTORROWS" type="i" access="readwrite">
   <annotation name="org.freedesktop.DBus.Property.EmitsChangedSignal" value="false"/>
  </property>
  <property name="NUMCONNECTORCOLUMNS" type="i" access="readwrite">
   <annotation name="org.freedesktop.DBus.Property.EmitsChangedSignal" value="false"/>
  </property>
 </interface>
-------------------------------------------------------------------------------------------------------------------------------------------
generated python code:
class OConnectorInterface(
    DbusInterfaceCommonAsync,
    interface_name='O.Connector',
):

    @dbus_property_async(
        property_signature='s',
    )
    def c_o_n_n_e_c_t_o_r_n_a_m_e(self) -> str:
        raise NotImplementedError

    @dbus_property_async(
        property_signature='s',
    )
    def c_o_n_n_e_c_t_o_r_k_i_n_d(self) -> str:
        raise NotImplementedError

    @dbus_property_async(
        property_signature='i',
    )
    def n_u_m_c_o_n_n_e_c_t_o_r_r_o_w_s(self) -> int:
        raise NotImplementedError

    @dbus_property_async(
        property_signature='i',
    )
    def n_u_m_c_o_n_n_e_c_t_o_r_c_o_l_u_m_n_s(self) -> int:
        raise NotImplementedError

**Comment by igo95862** [comment]
Using all capital letters method is very non-standard. (D-Bus specification tells to use CamelCase)

I plan on improving the interface generator in next version. I will include the improvement in handling multiple capital letters in sequence but not in the way your patch is doing it.

**Comment by bhattarabi** [comment]
Thank you!

**Comment by igo95862** [comment]
Should be fixed in ae7bda2aba53de25228fc0839f1afa90a357119f
