### ISSUE TITLE
GPLv2 license file

### ISSUE THREAD

**Issue by madeg-vaisala** [python-sdbus/python-sdbus#40]
Thanks for this great D-Bus library for Python! We might be interested in taking it into use in our projects.

The project is currently quite clearly flagged as being licensed under LGPL2.1. However, there is the "COPYING" file in the root which contains a GPLv2 license. What is the purpose the GPL license file? Is some part of the code GPL licensed?

**Comment by igo95862** [comment]
Hello @madeg-vaisala 

The license is LGPL-2.1-or-later as indicated by SPDX headers.

The reason why there is both `COPYING` and `COPYING.LESSER` files is GNU guideline:

https://www.gnu.org/licenses/gpl-howto.html

> Add a COPYING file with a copy of the GNU GPL or GNU AGPL.
> Also add a COPYING.LESSER file with a copy of the GNU LGPL, if you use that.

**Comment by madeg-vaisala** [comment]
Ok, that's clear then.

Studying this a bit more, I learned that LGPL is actually considered an extension of GPL, thus both files are indeed needed.

https://softwareengineering.stackexchange.com/questions/302433/why-does-the-lgpl-require-combined-works-to-include-a-copy-of-the-gpl
