### ISSUE TITLE
Derived properties in sdbus_async?

### ISSUE THREAD

**Issue by gotthardp** [python-sdbus/python-sdbus#44]
Hello. Is there a way to define "derived" properties in the `sdbus_async` scheme, please?

Let's say I have a "state" property that returns a number:
```python
class MMModemInterfaceAsync(DbusInterfaceCommonAsync, interface_name='org.freedesktop.ModemManager1.Modem'):
...
    @dbus_property_async(property_signature='u')
    def power_state(self) -> int:
        raise NotImplementedError
```
And I want another, "derived" property that returns a textual name of the state. In the `sdbus_block` we have this, but it obviously doesn't work in async:
```python
    @property
    def power_state_text(self) -> str:
        return MMModemPowerState(self.power_state).name
```
(One of) the trouble(s) is the following code in `python-sdbus` that does tries to retrieve the members and properties:
https://github.com/python-sdbus/python-sdbus/blob/23bc01c64f594992c7ba64a3a5cbf23453116592/src/sdbus/dbus_proxy_async_interfaces.py#L64-L75

It fails either because `ValueError: <sdbus.dbus_proxy_async_property.DbusPropertyAsyncBinded object at 0x7f127120fd90> is not a valid MMModemPowerState` or because `sys:1: RuntimeWarning: coroutine 'MMModem.power_state_text' was never awaited`, which is clear and obvious.

I wonder-- is there / could there be a way to have a property calculated based on an `dbus_property_async`? Or can I only have a async method like this:
```python
    async def get_power_state_text(self) -> str:
        return MMModemPowerState(await self.power_state).name
```

**Comment by gotthardp** [comment]
Thank you.

Not only that. I would like to (if possible) have a class derived from `DbusInterfaceCommonAsync` (interface or object) with a `@dbus_property_async` **and** a `@property` and call the `@dbus_property_async` from that `@property`. (To have an object/interface with this extra `@property`, just like one can extend an interface/object with an extra method that calls some d-bus method.)

Even when returning the awaitable as you suggest causes an error from the `getmembers`.
```
  File "/usr/local/lib64/python3.11/site-packages/sdbus/dbus_proxy_async_interfaces.py", line 72, in __init__
    for key, value in getmembers(self):
                      ^^^^^^^^^^^^^^^^
...
sys:1: RuntimeWarning: coroutine 'MMModem.power_state_text.<locals>.ret' was never awaited
```

**Comment by igo95862** [comment]
This isn't actually an error but a warning.

https://github.com/python-sdbus/python-sdbus/blob/23bc01c64f594992c7ba64a3a5cbf23453116592/src/sdbus/dbus_proxy_async_interfaces.py#L69-L77

This code isn't actually doing anything. Probably some remains of old code that should be removed.

**Comment by igo95862** [comment]
> Not only that. I would like to (if possible) have a class derived from `DbusInterfaceCommonAsync` (interface or object) with a `@dbus_property_async` **and** a `@property` and call the `@dbus_property_async` from that `@property`. (To have an object/interface with this extra `@property`, just like one can extend an interface/object with an extra method that calls some d-bus method.)

It should already be possible to mix `@property` and `@dbus_async_property`. However, it will probably be confusing on what will return an awaitable and what will instantly return a value.

**Comment by igo95862** [comment]
I will clean-up the unused code in the near future.

@gotthardp do you have any more questions.

**Comment by gotthardp** [comment]
It's all clear now. Thanks a lot!
