### ISSUE TITLE
Commit 1066153f broke python-sdbus-networkmanager

### ISSUE THREAD

**Issue by AndersBlomdell** [python-sdbus/python-sdbus#49]
With python-sdbus-netwokmanager 709b8d30, the following code

```
#!/usr/bin/python3

import sdbus
import sdbus_block.networkmanager
```

fails with:

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    import sdbus_block.networkmanager
  File "/usr/lib/python3.12/site-packages/sdbus_block/networkmanager/__init__.py", line 173, in <module>
    from .objects import (
  File "/usr/lib/python3.12/site-packages/sdbus_block/networkmanager/objects.py", line 217, in <module>
    class NetworkDeviceGeneric(
  File "/usr/local/lib64/python3.12/site-packages/sdbus-0.11.1-py3.12-linux-x86_64.egg/sdbus/dbus_proxy_sync_interface_base.py", line 84, in __new__
TypeError: Interface 'NetworkDeviceGeneric' and <class 'sdbus_block.networkmanager.interfaces_devices.NetworkManagerDeviceStatisticsInterface'> have interface name collision: {'org.freedesktop.DBus.Peer', 'org.freedesktop.DBus.Introspectable', 'org.freedesktop.DBus.Properties'}
```

**Comment by AndersBlomdell** [comment]
> By the way. Is there a reason why you are using the development versions?
Staying sharp at the bleeding edge :-)

But honestly I'm about to find a replacement for python-networkmanager https://github.com/seveas/python-networkmanager that is abandoned  by the author, and using development version during the startup phase usually gives fewer problems down the road (i.e. easier to get problems fixed in the development  branch)

**Comment by AndersBlomdell** [comment]
> Hello @AndersBlomdell
> 
> I think I see the issue. The non-serving interfaces should not be checked for name collisions. Async interfaces already have this but I never added a unit test for blocking interfaces multiple inheritance.

More to it than I can grasp :-( :
```
--- a/src/sdbus/dbus_proxy_sync_interface_base.py
+++ b/src/sdbus/dbus_proxy_sync_interface_base.py
@@ -46,7 +46,7 @@ class DbusInterfaceMetaSync(DbusInterfaceMetaCommon):
                 ) -> DbusInterfaceMetaSync:
 
         dbus_class_meta = DbusClassMeta()
-        if interface_name is not None:
+        if interface_name is not None and serving_enabled:
             dbus_class_meta.dbus_interfaces_names.add(interface_name)
 
         for attr_name, attr in namespace.items():
@@ -91,8 +91,8 @@ class DbusInterfaceMetaSync(DbusInterfaceMetaCommon):
                 )
 
             if dbus_member_collision := (
-                dbus_class_meta.dbus_member_to_python_attr.keys()
-                & base._dbus_meta.dbus_member_to_python_attr.keys()
+                namespace.keys()
+                & base._dbus_meta.python_attr_to_dbus_member.keys()
             ):
                 raise TypeError(
                     f"Interface {name!r} and {base!r} have D-Bus member "
```

Makes that error go away, but I skipped all the code relating to overrides in the async variant.

**Comment by igo95862** [comment]
@AndersBlomdell I pushed e7bd8dc1bc47ca50089efc8efc8a31a67cccf645 which should fix the issue. Could you give it a test?

I realized there is a big issue with how the D-Bus member to python attribute map is created. In D-Bus you can have the member share name if the belong to different interfaces but my current code does not account for that.

**Comment by AndersBlomdell** [comment]
Works for me! Thanks!

**Comment by igo95862** [comment]
FYI the master branch of NetworkManager binds is currently in the version 3.0 development.

https://github.com/python-sdbus/python-sdbus-networkmanager/commit/68485e6e0043cbb4ef75b99aec086d8a0cb44179

I started with renaming the enums to match the NetworkManager documentation.

**Comment by igo95862** [comment]
> Works for me! Thanks!

Great! Should I close the issue?

**Comment by AndersBlomdell** [comment]
> > Works for me! Thanks!
> 
> Great! Should I close the issue?
Please do!
