### ISSUE TITLE
-fPIC linker flag missing for arm64 cross compilation of shared library

### ISSUE THREAD

**Issue by BubuOT** [python-sdbus/python-sdbus#50]
I tried packaging python-sdbus in [buildroot](https://buildroot.org/) but encounterd he following link error:

```
/home/marcus/repos/buildroot_tmp/output/per-package/python-sdbus/host/bin/aarch64-linux-gcc -shared -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os -g0 -D_FORTIFY_SOURCE=1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 build/temp.linux-aarch64-cpython-311/src/sdbus/sd_bus_internals.o build/temp.linux-aarch64-cpython-311/src/sdbus/sd_bus_internals_bus.o build/temp.linux-aarch64-cpython-311/src/sdbus/sd_bus_internals_funcs.o build/temp.linux-aarch64-cpython-311/src/sdbus/sd_bus_internals_interface.o build/temp.linux-aarch64-cpython-311/src/sdbus/sd_bus_internals_message.o -L. -o build/lib.linux-aarch64-cpython-311/sdbus/sd_bus_internals.cpython-311-aarch64-linux-gnu.so -lsystemd -flto
/home/marcus/repos/buildroot_tmp/output/per-package/python-sdbus/host/opt/ext-toolchain/bin/../lib/gcc/aarch64-buildroot-linux-gnu/13.2.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/ccCSICoK.ltrans0.ltrans.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `SdBus_async_callback' which may bind externally can not be used when making a shared object; recompile with -fPIC
/tmp/ccCSICoK.ltrans0.ltrans.o: in function `SdBus_call_async':
<artificial>:(.text+0x5b38): dangerous relocation: unsupported relocation
/home/marcus/repos/buildroot_tmp/output/per-package/python-sdbus/host/opt/ext-toolchain/bin/../lib/gcc/aarch64-buildroot-linux-gnu/13.2.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/ccCSICoK.ltrans0.ltrans.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_SdBus_match_signal_instant_callback' which may bind externally can not be used when making a shared object; recompile with -fPIC
/tmp/ccCSICoK.ltrans0.ltrans.o: in function `SdBus_get_signal_queue':
<artificial>:(.text+0x5df0): dangerous relocation: unsupported relocation
/home/marcus/repos/buildroot_tmp/output/per-package/python-sdbus/host/opt/ext-toolchain/bin/../lib/gcc/aarch64-buildroot-linux-gnu/13.2.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/ccCSICoK.ltrans0.ltrans.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_SdBus_signal_callback' which may bind externally can not be used when making a shared object; recompile with -fPIC
<artificial>:(.text+0x5e00): dangerous relocation: unsupported relocation
/home/marcus/repos/buildroot_tmp/output/per-package/python-sdbus/host/opt/ext-toolchain/bin/../lib/gcc/aarch64-buildroot-linux-gnu/13.2.0/../../../../aarch64-buildroot-linux-gnu/bin/ld: /tmp/ccCSICoK.ltrans0.ltrans.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `SdBus_request_name_callback' which may bind externally can not be used when making a shared object; recompile with -fPIC
/tmp/ccCSICoK.ltrans0.ltrans.o: in function `SdBus_request_name_async':
<artificial>:(.text+0x5ff0): dangerous relocation: unsupported relocation
collect2: error: ld returned 1 exit status
error: command '/home/marcus/repos/buildroot_tmp/output/per-package/python-sdbus/host/bin/aarch64-linux-gcc' failed with exit code 1
```

I have to admit I don't fully understand what's going on but following the compiler advice I added the `-fPIC` *linker* flag (as the link step fails and all compiler invocations prior already used `-fPIC`) which seems to have fixed the build.
So the following patch was necessary and sufficient to get my build working. Not sure if this is also the right thing to do for the static library build though.

```
--- a/setup.py
+++ b/setup.py
@@ -73,6 +73,7 @@ if environ.get('PYTHON_SDBUS_USE_STATIC_LINK'):
                       '-Wl,-Bdynamic', '-lrt', '-lpthread']
 
 link_arguments.append('-flto')
+link_arguments.append('-fPIC')
 
 compile_arguments: List[str] = ['-flto']
```

**Comment by igo95862** [comment]
Hello @BubuOT 

I run `python setup.py build --force` on my machine and this is one the compile command I have:

```
gcc -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -ffat-lto-objects -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/python/src=/usr/src/debug/python -flto=auto **-fPIC** -g -I/usr/include/python3.11 -c src/sdbus/sd_bus_internals_message.c -o build/temp.linux-x86_64-cpython-311/src/sdbus/sd_bus_internals_message.o -flto
```

As you can see the python-setuptools enable the position independent code (PIC) by default.

Not sure about cross compilation. This might be a bug in python-setuptools.

My packages are `Python 3.11.6` and `python-setuptools 69.0.3`.

Also check for CFLAGS variable. You might be able to use it to force the PIC.

**Comment by igo95862** [comment]
> I don't understand why it's required though.

Might be some a bug in python-setuptools.

> I managed to solve this by adding -fPIC to the link command by forcing it though LDFLAGS environment variable now, so that's better than patching setup.py.

Great! Should I close the issue?

**Comment by BubuOT** [comment]
> Should I close the issue?

Fine by me at this point. It's here for further reference if someone runs into it while cross-compiling in the future.

**Comment by tpetazzoni** [comment]
Since I was reviewing the Buildroot patch from @BubuOT on this topic, I had a deeper look. The issue comes from the fact that python-sdbus's setup.py adds -flto in the compiler/linker flags. If you drop this, it all works fine.

Without LTO, passing fPIC during compilation is fine, passing it at link time is not needed.

When LTO is enabled, things are less clear. Some GCC bug reports such as https://gcc.gnu.org/bugzilla/show_bug.cgi?id=43659 seems to indicate that GCC is supposed to "remember" than the object files have been compiled with fPIC, and therefore automatically remember at link time that PIC code should be generated (with LTO, most of the code generation takes place at link time, not compile time). However clearly in our case, if one simply adds -fPIC to the link command line, it fixes the issue.

So I believe the next step would be to clarify this with the GCC people. If it's a GCC bug, it needs to be fixed there.

If it's not a GCC bug, and we must pass -fPIC, then it means that python-sdbus's setup.py cannot "blindly" add -flto, as it has more complicated implications and would probably need to be supported in setuptools to work correctly.

**Comment by igo95862** [comment]
I plan on replacing the `setup.py` with meson in 0.14.0. It will probably have a different LTO handling.
