### ISSUE TITLE
No signals on DbusPropertiesInterfaceAsync

### ISSUE THREAD

**Issue by satirebird** [python-sdbus/python-sdbus#6]
I am not so familiar with the dbus itself. I have tried to receive the signals from `DbusPropertiesInterfaceAsync.properties_changed` using the following code:

```
async def signal_changed():
    async for x in pr.properties_changed:
        print("Changed: ", x)

bus = sd_bus_open_system()
pr = DbusPropertiesInterfaceAsync.new_connect('org.bluez', '/', bus)

loop = get_event_loop()
task1 = loop.create_task(signal_changed())
loop.run_forever()
```
The I used `bluetoothctl` to change a property: `discoverable on` and `discoverable off`. The output of bluetoothctl reports the change:
```
[CHG] Controller XX:XX:XX:F6:A1:A1 Discoverable: yes
[CHG] Controller XX:XX:XX:F6:A1:A1 Discoverable: no
```
The running sdbus script reports nothing.

BTW: The dbus library takes additional parameters to setup a signal receivers:
```
        bus.add_signal_receiver(self.__interfaces_added,
                                dbus_interface="org.freedesktop.DBus.ObjectManager",
                                signal_name="InterfacesAdded")

        bus.add_signal_receiver(self.__properties_changed,
                            dbus_interface="org.freedesktop.DBus.Properties",
                            signal_name="PropertiesChanged",
                            arg0="org.bluez.Device1",
                            path_keyword="path")
```

**Comment by igo95862** [comment]
```
pr = DbusPropertiesInterfaceAsync.new_connect('org.bluez', '/', bus)
```
You are trying to listen to properties of the root object. (`/`)

You probably want to listen to a specific device properties. (for example `/org/bluez/hci0`)

Have you tried [D-Feet](https://wiki.gnome.org/Apps/DFeet)? It helps a lot in visualizing the dbus.

**Comment by satirebird** [comment]
You are right. The object path must match otherwise nothing will happen. I have to use `/org/bluez/hci0/dev_XX_XX_XX_4F_D3_BF` to listen to a specific device. This is different to the 'dbus' example. (I thought I can get everything if I use the root object.) 
Ok. I got it. 
Thank you very much.
(I use d-feet very often.)
