### ISSUE TITLE
Distribute the source on PyPi

### ISSUE THREAD

**Issue by souliane** [python-sdbus/python-sdbus#62]
Hi,

would it be possible to push the sources to PyPi?

We use this (awesome!) project for an embedded system, and need to re-package each dependency... It would be convenient to download the sources from PyPi, and not from the github repo.

Thanks!

**Comment by igo95862** [comment]
Hello @souliane ,

It looks like I forgot to upload the 0.12.0 source package. I will fix this today evening.

For comparison there is the `.tar.gz` package for version 0.11.1: https://pypi.org/project/sdbus/0.11.1/#files

**Comment by souliane** [comment]
Thanks a lot!

**Comment by souliane** [comment]
Awesome.

I also use AArch64, but for some [reason](https://hub.mender.io/t/how-to-work-with-python-applications-and-modules-in-yocto-project/1135) we need to build from the sources.

**Comment by igo95862** [comment]
I see.

Should I close the issue now that the source package was uploaded? I plan on improving the CI to check for source package on PyPI.

**Comment by souliane** [comment]
Yeah, sure. I was not sure if I should close it myself or leave it to you. Thanks :-)
