### ISSUE TITLE
Async Callback for match_signal_async() method?

### ISSUE THREAD

**Issue by wes8ty** [python-sdbus/python-sdbus#63]
Is there a way to continuously process a property-changed signal using an async callback method? I want to subscribe to the "org.bluez" interface to see when a phone connects/disconnects from Bluetooth. I was using `get_signal_queue_async` before but this has been replaced with `match_signal_async`. I tried making my callback async `_task_properties_changed` but nothing fired. When I changed it non-async, it fired properly but I need to call async methods based on the contents of this signal.

``` py
slot = await self._bus.match_signal_async("org.bluez", None, "org.freedesktop.DBus.Properties", "PropertiesChanged", self._task_properties_changed)
```

Thanks!

**Comment by igo95862** [comment]
Hello @wes8ty

Have you tried using the [`catch_anywhere`](https://python-sdbus.readthedocs.io/en/latest/asyncio_api.html#sdbus.DbusSignalAsync.catch_anywhere) method of the `properties_changed` signal?

```python
from asyncio import run

from sdbus import DbusInterfaceCommonAsync, sd_bus_open_system, set_default_bus


async def main() -> None:
    set_default_bus(sd_bus_open_system())

    async for path, data in DbusInterfaceCommonAsync.properties_changed.catch_anywhere("org.bluez"):
        print(path, data)


if __name__ == "__main__":
    run(main())
```

You can also use the [`sdbus.utils.parse_properties_changed`](https://python-sdbus.readthedocs.io/en/latest/utils.html#sdbus.utils.parse_properties_changed) to parse data of the signal in to the Python classes and the attribute names.

**Comment by igo95862** [comment]
> When I changed it non-async, it fired properly but I need to call async methods based on the contents of this signal.

Yes, because it uses the `call_soon` to run callbacks. However, you can still use the `get_running_loop().create_task()` to schedule run an async function from a blocking one. Remember to keep a reference to the task or it will be garbage collected.

**Comment by wes8ty** [comment]
Thanks @igo95862 ! I was trying to use `sdbus.utils.parse_properties_changed` but get the following error.

``` py
async for _, data in DbusInterfaceCommonAsync.properties_changed.catch_anywhere("org.bluez"):
    test = sdbus.utils.parse_properties_changed(DbusInterfaceCommonAsync, data)
```

```[Logs]    [2024-04-15T12:52:42.002Z] [cns_mngr] [ERROR] [MainThread] [blemngr.py          : 247] 'org.bluez.Device1'
[Logs]    [2024-04-15T12:52:42.003Z] [cns_mngr] Traceback (most recent call last):
[Logs]    [2024-04-15T12:52:42.003Z] [cns_mngr]   File "/usr/local/lib/python3.11/runpy.py", line 198, in _run_module_as_main
[Logs]    [2024-04-15T12:52:42.003Z] [cns_mngr]     return _run_code(code, main_globals, None,
[Logs]    [2024-04-15T12:52:42.004Z] [cns_mngr]   File "/usr/local/lib/python3.11/runpy.py", line 88, in _run_code
[Logs]    [2024-04-15T12:52:42.004Z] [cns_mngr]     exec(code, run_globals)
[Logs]    [2024-04-15T12:52:42.004Z] [cns_mngr]   File "/usr/app/cnsmngr/__main__.py", line 46, in <module>
[Logs]    [2024-04-15T12:52:42.004Z] [cns_mngr]     uvloop.run(cns_app.execute())
[Logs]    [2024-04-15T12:52:42.004Z] [cns_mngr]   File "/usr/app/.venv/lib/python3.11/site-packages/uvloop/__init__.py", line 105, in run
[Logs]    [2024-04-15T12:52:42.004Z] [cns_mngr]     return runner.run(wrapper())
[Logs]    [2024-04-15T12:52:42.010Z] [cns_mngr]   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
[Logs]    [2024-04-15T12:52:42.011Z] [cns_mngr]     return self._loop.run_until_complete(task)
[Logs]    [2024-04-15T12:52:42.011Z] [cns_mngr] > File "/usr/app/cnsmngr/ble/blemngr.py", line 226, in _task_properties_changed
[Logs]    [2024-04-15T12:52:42.011Z] [cns_mngr]     test = sdbus.utils.parse_properties_changed(DbusInterfaceCommonAsync, data)
[Logs]    [2024-04-15T12:52:42.011Z] [cns_mngr]   File "/usr/app/.venv/lib/python3.11/site-packages/sdbus/utils.py", line 73, in parse_properties_changed
[Logs]    [2024-04-15T12:52:42.011Z] [cns_mngr]     meta = DBUS_CLASS_TO_META[DBUS_INTERFACE_NAME_TO_CLASS[interface_name]]
[Logs]    [2024-04-15T12:52:42.011Z] [cns_mngr]   File "/usr/local/lib/python3.11/weakref.py", line 136, in __getitem__
[Logs]    [2024-04-15T12:52:42.011Z] [cns_mngr]     o = self.data[key]()
[Logs]    [2024-04-15T12:52:42.011Z] [cns_mngr] KeyError: 'org.bluez.Device1'
```

**Comment by igo95862** [comment]
Calling it with `sdbus.utils.parse_properties_changed` with only `DbusInterfaceCommonAsync` does not make much sense. It is useful when you have multiple interfaces classes (which inherit from `DbusInterfaceCommonAsync`) and using it you can parse the signal data in to the interface class and the python properties.

If you only need to check then the device connected you can probably just use the raw dictionary. 

This is what I got from the script I posted when I connected and disconnected a bluetooth device

```
/org/bluez/hci0/dev_00_00_00_00_00_00 ('org.bluez.Device1', {'Connected': ('b', True)}, [])
/org/bluez/hci0/dev_00_00_00_00_00_00 ('org.bluez.Device1', {'Connected': ('b', False)}, [])
```

The data is a tuple of 3 elements and the second element is the variant dictionary.

**Comment by wes8ty** [comment]
Got it. Thanks so much!
