### ISSUE TITLE
Please use "~" for separator for RC tags

### ISSUE THREAD

**Issue by bluca** [python-sdbus/python-sdbus#64]
`0.12.RC1` orders as newer than `0.12` in the vast majority of packaging and other tools:

```
$ dpkg --compare-versions 0.12 gt 0.12.RC1; echo $?
1
```

Please use `0.12~rc1` next time around, so that everything works out of the box when watching for new versions, comparing tags, etc.

**Comment by igo95862** [comment]
Hello @bluca 

Thank you for pointing this out. I think I will use the `0.12rc1` form because this is what the Python packaging normalizes to.

```python
import packaging.version

ver = packaging.version.parse('0.12.rc1')
print(ver)  # Prints <Version('0.12rc1')>
```

It seems to pass the debian version check:

```shell
dpkg --compare-versions 0.12.0 gt 0.12rc1; echo $?
# 0
```

**Comment by bluca** [comment]
That is also not guaranteed to work. Please just use `~`, it's the standard separator that automatically means "this is smaller than the same number without the ~ part" and it is universally understood

**Comment by igo95862** [comment]
The tilde does not work with Python packaging versioning.

```python
import packaging.version

packaging.version.parse("0.12~rc1")
# packaging.version.InvalidVersion: Invalid version: '0.12~rc1'
```

Also I've never seen a project that uses tilde to separate RC tags.

For example, systemd uses dash: https://github.com/systemd/systemd/tags

Pacman just appends the tag: https://archlinux.org/pacman/#_releases

**Comment by igo95862** [comment]
Meson uses the `1.4.0rc2` method: https://github.com/mesonbuild/meson/tags

**Comment by igo95862** [comment]
Looking at the semver specification: https://semver.org/

> A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1,

> Example: 1.0.0-alpha < 1.0.0-alpha.1 < 1.0.0-alpha.beta < 1.0.0-beta < 1.0.0-beta.2 < 1.0.0-beta.11 < 1.0.0-rc.1 < 1.0.0.

However, this does not work with pacman's vercmp. It looks like every packaging tool has its own versioning limitations.

For example, Arch Linux modifies the systemd versions: https://gitlab.archlinux.org/archlinux/packaging/packages/systemd/-/blob/ccc32ea10164a9b6ca3098765e63f653cddc6817/PKGBUILD#L10

I guess I found a first ever reference to tilde.

**Comment by igo95862** [comment]
I found a specification that uses the tilde: https://uapi-group.org/specifications/specs/version_format_specification/#version-format

@bluca are you referencing those specifications? I can adopt tilde once it is actually universal. Right now the biggest issue is PyPI which does not work with tilde. The lowest common denominator seems to be `0.12rc1` format which works across PyPI,dpkg and pacman.

**Comment by igo95862** [comment]
Looks like Debian tracker correctly now shows the 0.13.0 as being the latest version: https://tracker.debian.org/pkg/python-sdbus

**Comment by igo95862** [comment]
@bluca I think Debian is not detecting the new `0.14.1` version I released a few days ago: https://tracker.debian.org/pkg/python-sdbus
