### ISSUE TITLE
Use `bound` instead of `binded`

### ISSUE THREAD

**Issue by souliane** [python-sdbus/python-sdbus#65]
There are a few classes like `DbusBindedAsync` that should IMHO be renamed to use `bound` instead of `binded`.

I am not a native speaker, but the correct conjugation seems to be `bound` (e.g. this [source](https://writingexplained.org/binded-or-bound), but there are many others).

**Comment by igo95862** [comment]
Yes, the name is pretty bad.

Those objects actually are the descriptors: https://docs.python.org/3/glossary.html#term-descriptor

> When a class attribute is a descriptor, its special binding behavior is triggered upon attribute lookup.

But I am not sure what is the correct name for what the descriptor returns from its `__get__` method.

**Comment by igo95862** [comment]
Another alternative naming is drop the bind name all together.

For example,

*  `DbusMethodAsync`: D-Bus method not accessed from any specific object (or accessed from class)
  * `DbusLocalMethodAsync` - D-Bus method accessed from a local object
  * `DbusProxyMethodAsync` - D-Bus method accessed from a proxy object

Can also be `LocalDbusMethodAsync` / `ProxyDbusMethodAsync`. What do you think @souliane ?

**Comment by souliane** [comment]
Hey, sorry for the late reply.
Honestly, I don't have any preference... Beside the fact that `binded` sounds wrong, I am OK with the current naming.
Feel free to pick whatever names you prefer :-)

**Comment by igo95862** [comment]
Fixed by @dragomirecky in 1fbc7ce9f9f6e406dc7747783af6f3fa750627ce
