### ISSUE TITLE
Unable to call a dbus method twice with asyncio.run

### ISSUE THREAD

**Issue by damienklotz77** [python-sdbus/python-sdbus#69]
Hi,

I have the following server :

```
import sdbus
import asyncio

loop = asyncio.new_event_loop()


class MyClass(sdbus.DbusInterfaceCommonAsync, interface_name="my.interface"):

    @sdbus.dbus_method_async(result_signature="s")
    async def myMethod(self):
        return "myString"

myObject = MyClass()

async def startup():
    await sdbus.request_default_bus_name_async("my.bus")
    myObject.export_to_dbus("/my/path")


loop.run_until_complete(startup())
loop.run_forever()
```

And the following client :

```
import sdbus
import asyncio


class MyClass(sdbus.DbusInterfaceCommonAsync, interface_name="my.interface"):
    @sdbus.dbus_method_async(result_signature="s")
    async def myMethod(self):
        pass


proxy = MyClass.new_proxy(service_name="my.bus", object_path="/my/path")


async def call_method():
    result = await proxy.myMethod()
    print(result)


asyncio.run(call_method())
asyncio.run(call_method())
```

**Test 1**

The first call to `call_method()` displays "myString" properly but the second call is stuck in following call :
`result = await proxy.myMethod()`

**Test 2**

When I replace following code
```
asyncio.run(call_method())
asyncio.run(call_method())
```
by
```
loop = asyncio.new_event_loop()
task = loop.create_task(call_method())
loop.run_until_complete(task)
task = loop.create_task(call_method())
loop.run_until_complete(task)
loop.close()
```
It is working properly.

**Test 3**

When I replace following code
```
asyncio.run(call_method())
asyncio.run(call_method())
```
by
```
loop = asyncio.new_event_loop()
task = loop.create_task(call_method())
loop.run_until_complete(task)
loop.close()
loop = asyncio.new_event_loop()
task = loop.create_task(call_method())
loop.run_until_complete(task)
loop.close()
```
The first call to `call_method()` displays "myString" properly but the second call is stuck in following call :
`result = await proxy.myMethod()`
Like in Test 1.

I have the feeling that the two methods calls work properly when using the same event loop.

Is this behaviour normal ?

For information, my environment is following :
- Ubuntu 22.04
- Python 3.10.12
- Python sdbus 0.12.0

Thank you

**Comment by igo95862** [comment]
Hello @damienklotz77 

> I have the feeling that the two methods calls work properly when using the same event loop.

The `asyncio,.run` actually creates a new event loop for every invocation:

 https://github.com/python/cpython/blob/2078eb45ca0db495972a20fcaf96df8fcf48451d/Lib/asyncio/runners.py#L137

The python-sdbus currently only registers the file descriptor listener once per bus so if a bus switches the file descriptor listener is not going to be re-registered meaning async calls will never be processed.

**Comment by igo95862** [comment]
Also you don't need to define the interface twice. The client can import the interface from the server.

**Comment by igo95862** [comment]
Try running this code:

```python
import asyncio


async def one():
    loop = asyncio.get_running_loop()
    future = loop.create_future()
    loop.call_later(3, future.set_result, None)
    return future


async def two(future) -> None:
    await future
    print("Awaited")


if __name__ == "__main__":
    fut = asyncio.run(one())
    asyncio.run(two(fut))
```

What will happen is that an exception will be raised:

```
RuntimeError: Task <Task pending name='Task-4' coro=<two() running at ./issue_69.py:12> cb=[_run_until_complete_cb() at /usr/lib/python3.12/asyncio/base_events.py:182]> got Future <Future pending> attached to a different loop
```

As you can see using `asyncio.run` twice is clearly an error.

I will investigate if it is possible for python-sdbus to raise an error as well but it has to do so in a way that does not affect performance.

**Comment by damienklotz77** [comment]
Thank you igo95862 for the quick response.

Yes, I use generated code for interface in both client and server.
I just wrote a minimalist example in this github issue to focus on the event loop problem.

Ok to keep using the same event loop accross the entire application life cycle for example with following code :

```
loop = asyncio.new_event_loop()
task = loop.create_task(call_method())
loop.run_until_complete(task)
task = loop.create_task(call_method())
loop.run_until_complete(task)
loop.close()
```

Just for curiosity, concerning the following design
"The python-sdbus currently only registers the file descriptor listener once per bus so if a event loop switches the file descriptor listener is not going to be re-registered meaning async calls will never be processed."
Would it be possible to make python-sdbus update the file descriptor record on the bus if an event loop changes ?

Thank you for your help :-)

**Comment by igo95862** [comment]
> Would it be possible to make python-sdbus update the file descriptor record on the bus if an event loop changes ?

Yes, it is possible but I want to evaluate the performance impact.

**Comment by damienklotz77** [comment]
Ok great, thank you igo95862 :-)

**Comment by igo95862** [comment]
a79a6557ac47a3ee15ba05423a15f466847c7cde should make it raise a RuntimeError if the bus is attempted to be shared between event loops.
