### ISSUE TITLE
Access denied when calling dbus method from another user

### ISSUE THREAD

**Issue by damienklotz77** [python-sdbus/python-sdbus#75]
Hi,

First thank you for this awesome python dbus library :-)

I am currently having an issue when trying to call dbus method of sdbus server from another Linux user (using system bus).

```
su user1
python sdbus_server.py
```

```
su user1
busctl call com.example.MyService1 /com/example/MyService1 com.example.MyService1.MyInterface MyMethod
i 0
```

```
su user2
busctl call com.example.MyService1 /com/example/MyService1 com.example.MyService1.MyInterface MyMethod
Call failed: Access denied
```

**How to reproduce**

Create new VM with Ubuntu 22.04 and user "user1".
Login to user1.

Create new following file "com.example.MyService1.xml" :

```
<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"https://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
 <interface name="com.example.MyService1.MyInterface">
  <method name="MyMethod">
   <arg type="i" direction="out"/>
  </method>
 </interface>
</node>
```

Generate python dbus interface :
```
source venv/bin/activate
python -m sdbus gen-from-file com.example.MyService1.xml > com_example_myservice1.py
```

Create new following configuration file :
/etc/dbus-1/system.d/com.example.MyService1.conf
with following content :

```
<?xml version="1.0"?>

<!DOCTYPE busconfig PUBLIC
 "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">

<busconfig>
  <policy context="default">
    <allow own="com.example.MyService1"/>
    <allow send_interface="com.example.MyService1.MyInterface"/>
  </policy>
</busconfig>
```

Create new following python file "sdbus_server.py" :

```
import asyncio
import sdbus
from sdbus import dbus_method_async_override
import com_example_myservice1

class ComExampleMyService1MyInterface(com_example_myservice1.ComExampleMyService1MyInterfaceInterface):

    @dbus_method_async_override()
    async def my_method(self) -> int:
        return 0

sdbus.set_default_bus(sdbus.sd_bus_open_system())

object = ComExampleMyService1MyInterface()
object.export_to_dbus("/com/example/MyService1")

loop = asyncio.get_event_loop()
loop.run_until_complete(sdbus.request_default_bus_name_async("com.example.MyService1"))
loop.run_forever()
```

Add new user "user2" :
`sudo adduser user2`

Run server on "user1" with :
`python sdbus_server.py`

In another terminal, do :
`busctl call com.example.MyService1 /com/example/MyService1 com.example.MyService1.MyInterface MyMethod`
Ansewer is :
`i 0`

Then :
```
su user2
busctl call com.example.MyService1 /com/example/MyService1 com.example.MyService1.MyInterface MyMethod
```
Answer is :
`Call failed: Access denied`

**Now trying with other python dbus library "dbus-python" :**

Execute following commands :
```
sudo apt install libdbus-1-dev libgirepository1.0-dev libcairo2-dev
pip install dbus-python PyGObject
```

Create following file "dbus_server.py"

```
from dbus.mainloop.glib import DBusGMainLoop
from gi.repository import GLib
import dbus
import dbus.bus
import dbus.service


class MyStub(dbus.service.Object):
    def __init__(self):
        DBusGMainLoop(set_as_default=True)
        mainloop = GLib.MainLoop()
        bus = dbus.Bus(dbus.Bus.TYPE_SYSTEM)
        bus.request_name(name="com.example.MyService1")
        bus_name = dbus.service.BusName(*["com.example.MyService1", bus])
        dbus.service.Object.__init__(self, object_path="/com/example/MyService1", bus_name=bus_name)
        mainloop.run()

    @dbus.service.method(dbus_interface="com.example.MyService1.MyInterface", out_signature="i")
    def MyMethod(self):
        return 0


if __name__ == "__main__":
    stub = MyStub()
```

Run server with :
`python dbus_server.py`

In another terminal, do :
`busctl call com.example.MyService1 /com/example/MyService1 com.example.MyService1.MyInterface MyMethod`
Ansewer is :
`i 0`

Then :
```
su user2
busctl call com.example.MyService1 /com/example/MyService1 com.example.MyService1.MyInterface MyMethod
```
Answer is :
`i 0`

So accessing to another user dbus server is working with python lib dbus-python.
So for me, it should work with "sdbus" too.

Maybe I am missing some sdbus configuration somewhere ?

Thank you in advance for your help, I really need this for my project ;-)

**Environment :** 
Linux : Ubuntu 22.04
Python : 3.10.12
sdbus :  0.12.0
dbus-python : 1.3.2

Damien Klotz

**Comment by igo95862** [comment]
Hello @damienklotz77 

I think the sd-bus has a built-in access control. If you call any method on the interface as another user your call will be validated against access controls.

I believe there is an unprivileged flag that you can add to a method definition to make it callable by anyone.

https://github.com/python-sdbus/python-sdbus/blob/266fca55fec67e4b135e8704118ee2db24cf004a/src/sdbus/__init__.py#L87

**Comment by igo95862** [comment]
Hmmm..., yes it looks like unprivileged flag has to be set everywhere the `org.freedesktop.systemd1.Privileged` is missing. See the system interfaces definitions:

https://github.com/systemd/systemd/blob/70bc8b3f0ce17fde7b8af983b0716393abaa39a4/src/core/dbus-manager.c#L3160

I will add a fix for this.

**Comment by igo95862** [comment]
With 01a0e44b2fdd0f2f292ead6125c254347d73cbd9 the code generator should properly set the unprivileged flag everywhere the `org.freedesktop.systemd1.Privileged` is not used.
