### ISSUE TITLE
Unique interface names required

### ISSUE THREAD

**Issue by gergelyk** [python-sdbus/python-sdbus#77]
What I understand from the code is that `DBUS_INTERFACE_NAME_TO_CLASS` binds unique names of dbus interfaces with corresponding Python classes. What if I need two interfaces of the same name but located under different objects and having different implementation? E.g.
```
my.service
  /my/service/object1
    my.desired.interface
      someMethod()
  /my/service/object2
    my.desired.interface
      someOtherMethod()
```
Do I understand correctly that python-sdbus doesn't support such scenario? Is there any workaround?
This is actually a real-life example encountered while working with BlueZ.

**Comment by igo95862** [comment]
Hello @gergelyk 

You can merge the `my.desired.interface` can then you can use a single interface under both paths. Using same interface name for two different implementation is a bad practice so I wanted to prevent that.  I might lift this limitation in the next version.

> This is actually a real-life example encountered while working with BlueZ.

By the way which interfaces are like that? I was planning on working on BlueZ binds at some point.

**Comment by gergelyk** [comment]
I see. I have seen your WIP with BlueZ.

Unless I'm mistaken, BlueZ requires each characteristic to be represented by `org.bluez.GattCharacteristic1` object. Each of them may have different implementation. The interface remains the same though:

```
-> /com/example
  |   - org.freedesktop.DBus.ObjectManager
  |
  -> /com/example/service0
  | |   - org.freedesktop.DBus.Properties
  | |   - org.bluez.GattService1
  | |
  | -> /com/example/service0/char0
  | |     - org.freedesktop.DBus.Properties
  | |     - org.bluez.GattCharacteristic1
  | |
  | -> /com/example/service0/char1
  |   |   - org.freedesktop.DBus.Properties
  |   |   - org.bluez.GattCharacteristic1
  |   |
  |   -> /com/example/service0/char1/desc0
  |       - org.freedesktop.DBus.Properties
  |       - org.bluez.GattDescriptor1
  |
  -> /com/example/service1
    |   - org.freedesktop.DBus.Properties
    |   - org.bluez.GattService1
    |
    -> /com/example/service1/char0
        - org.freedesktop.DBus.Properties
        - org.bluez.GattCharacteristic1
```
Source: https://github.com/luetzel/bluez/blob/master/doc/gatt-api.txt

As you suggested, merging solves the problem. I used the following pattern:
```python
class OrgBluezCharacteristicInterface(
    DbusInterfaceCommonAsync,
    interface_name='org.bluez.GattCharacteristic1'
):

    @dbus_property_async(
        property_signature='s',
        property_name='UUID'
    )
    def uuid(self) -> str:
        return self._uuid

class OrgBluezFirstCharacteristicInterface(OrgBluezCharacteristicInterface):

    _uuid = '0x2A01'

class OrgBluezSecondCharacteristicInterface(OrgBluezCharacteristicInterface):

    _uuid = '0x2A02'
    
characteristic1 = OrgBluezFirstCharacteristicInterface()
characteristic2 = OrgBluezSecondCharacteristicInterface()

characteristic1.export_to_dbus('/org/bluez/app/service0/chrc1')
characteristic2.export_to_dbus('/org/bluez/app/service0/chrc2')
```

We can close this thread. Thank you!
