### ISSUE TITLE
Can't get to a unit's properties/methods

### ISSUE THREAD

**Issue by polymerchm** [python-sdbus/python-sdbus#79]
Consused;   Trying to simply tell if a service "wifi-connect" is running for not.   I know there are other ways, but like this appoach.   I am using the NetworkManager implementation succesfully.  

Can't  figure out what call to get access to the methods in the SystemdUnit class. For services that I now are running, I can get the object path "/org/freedesktop/systemd1/unit/ssh_2eservice", but when I used that in a call to SystemdUnit and then try to access a property, I get an 'Transport endpoint is not connected' error.

**Comment by igo95862** [comment]
Hello @polymerchm 

Can you post the code and the error logs?

The 'Transport endpoint is not connected' might mean the bus got disconnected but I can't say for sure without looking in to the code, error logs and how you are running the code.

**Comment by polymerchm** [comment]
import sdbus
from sdbus_block.systemd import (
    SystemdUnit,
    SystemdInterface,
    Systemd
)

def is_service_active(service: str)->bool:
        
    """
    use sdbus to check on statue of service
    
    """
    systemd = Systemd(sdbus.sd_bus_open_system())
    try:
        unit_object_path = systemd.get_unit(service)
    except Exception as e:
        print(f"no such unit {e}")
        sys.exit()
    unit = SystemdUnit(unit_object_path)
    print(unit.description)

    return True


    

if __name__=="__main__":
    service = "ssh.service"
    print(f" is the the service {service} running? -> {is_service_active(service)}")

**Comment by igo95862** [comment]
Not familiar with `python-sdbus-systemd` (you should ask @bernhardkaindl) but one thing certain is that you want to set the system D-Bus as default before initializing any objects:

```python
import sdbus
from sdbus_block.systemd import (
    SystemdUnit,
    SystemdInterface,
    Systemd
)

def is_service_active(service: str)->bool:
        
    """
    use sdbus to check on statue of service
    
    """
    systemd = Systemd()
    try:
        unit_object_path = systemd.get_unit(service)
    except Exception as e:
        print(f"no such unit {e}")
        sys.exit()
    unit = SystemdUnit(unit_object_path)
    print(unit.description)

    return True


    

if __name__=="__main__":
    sdbus.set_default_bus(sdbus.sd_bus_open_system())
    service = "ssh.service"
    print(f" is the the service {service} running? -> {is_service_active(service)}")
```

Also I would recommend trying to run it without the vscode debugger as it could affect the bus connection in unpredictable way.

**Comment by polymerchm** [comment]
I figured out that I was not setting the default bus.   Works quite well in and out of the vscode debugger, as does the NetworkManager code.   Thanks for all the heavy lifting on these libraries.

**Comment by igo95862** [comment]
Should I close the issue now that you found the solution?
