### ISSUE TITLE
`new_connect` does not fail when the interface does not actually exist

### ISSUE THREAD

**Issue by turbinenreiter** [python-sdbus/python-sdbus#8]
Hi!

We are using the `new_connect` to get the proxy object of a daemon. Surprisingly, it does not fail when the don't actually run the daemon that we are connecting too.

Is this a bug or a design decision (and we are using it wrong)?

Thanks.

**Comment by igo95862** [comment]
I have released version 0.8.4. It comes with the renames of the methods. Old methods will be removed in 1.0.0
