### ISSUE TITLE
Interface Generator Outputs Python Keywords as Method Names

### ISSUE THREAD

**Issue by jamesg-nz** [python-sdbus/python-sdbus#9]
If D-Bus name is a Python keyword than that gets output into the Python source code as a method name which is invalid.

Suggest using built-in [Python keyword module](https://docs.python.org/3/library/keyword.html) to test for keywords, then escape them in here:

https://github.com/python-sdbus/python-sdbus/blob/820dd7003ee6200b68a829e7176aa6957765c2fe/src/sdbus/interface_generator.py#L56-L57

A trailing (or preceding) underscore added to the snake case would result in valid Python code, and get ignored in conversion back to camel case at runtime.

**Comment by igo95862** [comment]
Preceding underscore will result in method becoming private.

It is possible to include a name conversion however the code generated should be inspected before running and fixed. ( for example, the formatting is broken)

I am actually wondering what D-Bus interface from what program caused collision with keyword?

**Comment by jamesg-nz** [comment]
Yeah - so trailing it would need to be.

The BlueZ `org.bluez.Adapter1` interface contains a property named `Class`.

Provided your PC has Bluetooth run this to see it:

```
$ python -m sdbus gen-from-connection --system org.bluez /org/bluez/hci0 | grep -n "def class"
86:    def class(self) -> int:
```

Guess bad lack I picked that interface first time I used the tool. Threw me a bit because not familiar with the tool and library.

**Comment by igo95862** [comment]
Code generator was mostly intended to do the most repetitive tasks of translating interfaces. The generated code definitely requires a human pass before it can be used.


I think the biggest issue is that Bluez binds package has not been made yet. For example, [NetworkManager has had binds for quite a while](https://github.com/python-sdbus/python-sdbus-networkmanager).

**Comment by igo95862** [comment]
@jamesg-nz 

I started with BlueZ binds here: https://github.com/python-sdbus/python-sdbus-bluez

You can help by posting introspection XML in this thread: https://github.com/python-sdbus/python-sdbus-bluez/issues/1
